#!/bin/sh

#引数チェック
if [ $# -eq 3 ] ; then
	filename=$1
	pagetitile=$2
	reportnumber=$3

else
	echo "Usage: prompt > $0 filename title reportnumber"
	exit 1

fi

if [ ! -e "$filename".tex ] ; then

cat << EOF >$filename.tex
%プリアンブル設定{{{
\documentclass[10pt]{jsarticle} %記事や論文を書く際にjarticleを使用

%枠付文章とpng画像を出力するため
\usepackage{ascmac}%枠付き文字出力
\usepackage{fancybox}
\usepackage{framed}
\usepackage[dvipdfmx]{graphicx}%pdf出力のための
\usepackage{mediabb}
\usepackage{here}
\usepackage{amsmath,amssymb}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[dvipdfmx,setpagesize=false]{hyperref}
\usepackage{pxjahyper}

\setcounter{tocdepth}{3}


%\usepackage{listings,jlisting}.cをpdfに出力
\usepackage{listings, jlisting}
\lstset{
  language={c},%言語名前
  basicstyle={\footnotesize\ttfamily},%ソースコードのフォント設定
  identifierstyle={\small},
  ndkeywordstyle={\small},
  keywordstyle={\ttfamily},
  stringstyle={\small\ttfamily},
  frame={tb},
  breaklines=true,%行が長くなった際の改行の有無
  xrightmargin=0zw,%右の余白の大きさ
  xleftmargin=3zw,%左の余白の大きさ
  numbers=left,%行番号表示場所
  stepnumber=1,%行番号の増分
  numbersep=1zw,%行番号と本文の間隔
  numberstyle=\ttfamily,
  frame=tRBl,
  framesep=5pt,
  commentstyle={\ttfamily},%コメントアウトのフォント設定
  flexiblecolumns = true,
  classoffset=1,
  showstringspaces=false,
  tabsize=4
}

%表と図を並べる
\makeatletter
    \renewcommand{\thefigure}{%
        \thesection.\arabic{figure}}
    \@addtoreset{figure}{section}
      \renewcommand{\thetable}{%
         \thesection.\arabic{table}}
	     \@addtoreset{table}{section}
\newcommand{\figcaption}[1]{\def\@captype{figure}\caption{#1}}
\newcommand{\tblcaption}[1]{\def\@captype{table}\caption{#1}}
\makeatother


%本文領域を広め（空白箇所マージン領域を小さめ）に設定
\setlength{\oddsidemargin}{-5mm}%文字の左からの間隔
\setlength{\topmargin}{-13mm}%用紙の上からの間隔
\setlength{\headheight}{12pt}%ヘッダーの高さ
\setlength{\headsep}{25pt}%ヘッダーとボディとの間隔
\setlength{\textwidth}{170mm}%文字出力の横幅を設定
\setlength{\textheight}{245mm}%文字出力の縦幅を設定
\setlength{\marginparwidth}{20pt}%注釈用の余白
\setlength{\footskip}{30pt}%フッターとボディとの間隔
\setlength{\evensidemargin}{-1cm}
\thispagestyle{empty}

%}}}

%表紙{{{
\begin{document}
\begin{titlepage}
    \begin{center} %vspaceは縦方向のスペースで，hspaceは横方向のスペース
        \fontsize{50pt}{50pt}\selectfont %フォントサイズと行送りを設定
        \vspace*{200truept}
        \bf{$pagetitile}\\\\ %タイトル1行目
       	\vspace{5truept}
		\fontsize{25pt}{50pt}\selectfont
		\bf{Report\#$reportnumber}
        \vspace{240truept}
    \end{center}
    \begin{flushright}
        {\large
            \fontsize{16pt}{0pt}\selectfont
          所  属  :バカ田大学 工学部 情報工学科\\\\
            \vspace{5truept}
          学籍番号:1192TKROKMKRBKF\\\\
            \vspace{5truept}
          氏  名  :バカボンのパパ\\\\
            \vspace{5truept}
          提 出 日:{\today}\\\\
            \vspace{5truept}
        }
    \end{flushright}
\end{titlepage}

\pagenumbering{roman}
\tableofcontents %目次を自動作成するコマンド

\pagestyle{plain}

\newpage
%}}}

\pagenumbering{arabic}

\section{}
\subsection{}
hoge
%\begin{figure}[h]
%  \includegraphics[width=1.0\textwidth]{./.pdf}
%\end{figure}






%\begin{thebibliography}{9}
%  \bibitem{}
%\end{thebibliography}

\end{document}

EOF

else
	    echo "Usage: prompt> Already file $filename.tex"
		exit 1
	fi


latexmk $filename
open ${filename}.pdf
echo make success $filename.pdf

vi ${filename}.tex
