#!/bin/sh
#カレントディレクトリの.styを自動追加

files=`ls -1 *.sty`
texpath=`/usr/local/texlive/2015basic/texmf-local/tex/latex/`


if [ ${files} -z ] ; then
    exit 1
fi

for file in $files
do
    filename=`echo $file | cut -f1 -d'.'`
    echo sudo mkdir -p -v ${texpath}${filename}

    sudo mkdir -p -v ${texpath}${filename}

    echo sudo mv ${file} ${texpath}${filename}
    sudo mv ${file} ${texpath}${filename}
done

sudo mktexlsr




