#!/bin/sh

timecheck=`date "+%H%M"`

#echo $timecheck

declare -a random=($(($RANDOM % 2)))

if [ $random = 0 ] ; then
    txt=`cat ./kuzu_pun/kinu_rap.txt`
elif [ $random = 1 ] ; then
    txt=`cat ./kuzu_pun/namatsutarap.txt`

fi

echo  "$txt"
