#!/bin/sh

timecheck=`date "+%H%M"`

if [ $timecheck = 2359 ] ; then
    txt=`cat ./kuzu_pun/23:59:20.txt`
    echo "$txt"
    exit 0
fi
#echo $timecheck

declare -a random=($(($RANDOM % 3)))

if [ $random = 0 ] ; then
    txt=`cat ./kuzu_pun/kinu_rap.txt`
elif [ $random = 1 ] ; then
    txt=`cat ./kuzu_pun/namatsutarap.txt`
elif [ $random = 2 ] ; then
    txt=`cat ./kuzu_pun/ika.txt`

fi

echo  "$txt"
